run:
  # if you are daring, set this to true
  tests: false

linters:
  enable:
    - gofmt
    - bodyclose
    - exhaustive
    - dupl
    - errorlint
    - prealloc
    - importas
    - errorlint
    - errname
    - revive
    - gocritic
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - misspell
    - goimports
    - tenv
    # - gochecknoglobals
    - gochecknoinits
    # - gci
    - usestdlibvars
    - thelper
    - nolintlint
    - noctx
    - wrapcheck
    - gocognit
    - sloglint

linters-settings:
  # importas:
  # if set to `true`, force to use alias.
  # no-unaliased: true
  # List of aliases
  # alias:
  #   - pkg: github.com/opencontainers/go-digest
  #     alias: digest

  exhaustive:
    default-signifies-exhaustive: true

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.19"
    # https://staticcheck.io/docs/options#checks
    checks: ["all"]

  revive:
    ignore-generated-header: true
    severity: warning
    # enable-all-rules: true
    # rules:
    # - name: banned-characters
    #   arguments: [""]
    # - name: line-length-limit
    #   severity: warning
    #   arguments: [200]
    # - name: function-result-limit
    #   arguments: [4]
    rules:
      - name: atomic
      # - name: line-length-limit
      #   severity: warning
      #   arguments: [120]
      - name: unhandled-error
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      # - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: defer
      - name: useless-break
      - name: unexported-naming
      # - name: cognitive-complexity
      #   arguments: [35]
      - name: use-any

  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    # Default: ""
    local-prefixes: git.act3-ace.com/ace

  wrapcheck:
    ignoreSigs:
      # defaults
      - ".Errorf("
      - ".Err("
      - "errors.New("
      - "errors.Unwrap("
      - ".Wrap("
      - ".Wrapf("
      - ".WithMessage("
      - ".WithMessagef("
      - ".WithStack("
      # expected to work
      - .ExecuteContext( # cobra command
      - (*golang.org/x/sync/errgroup.Group).Wait()
      - fs.ReadDir
    ignoreSigRegexps:
      # ignore printing (to stdout)
      - "fmt\\..?(P|p)rint.*\\("
    ignorePackageGlobs:
      - encoding/*
      - git.act3-ace.com/* # Only catches things when they are imported

  gocognit:
    min-complexity: 35
  
  sloglint:
    # Enforce not mixing key-value pairs and attributes.
    # Default: true
    # no-mixed-args: false

    # Enforce using key-value pairs only (overrides no-mixed-args, incompatible with attr-only).
    # Default: false
    # kv-only: true

    # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
    # Default: false
    # attr-only: true

    # Enforce using methods that accept a context.
    # Default: false
    context-only: true

    # Enforce using static values for log messages.
    # Default: false
    static-msg: true

    # Enforce using constants instead of raw keys.
    # Default: false
    # no-raw-keys: true

    # Enforce a single key naming convention.
    # Values: snake, kebab, camel, pascal
    # Default: ""
    key-naming-case: snake

    # Enforce putting arguments on separate lines.
    # Default: false
    # args-on-sep-lines: true

issues:
  # uncomment to enable more linting
  exclude-use-default: false

  include:
    - EXC0005
    - EXC0012
    - EXC0009
    - EXC0002
    - ST1000
